waternsw:
  target: prod
  outputs:
    prod:
      type: snowflake
      account: SFSEAPAC-AAPALIS_AZURE1
      database: WATERNSW
      warehouse: COMPUTE_WH
      schema: PUBLIC
      role: SYSADMIN
